### ISSUE TITLE
Hide spinner issue

### ISSUE THREAD

**Issue by MykhailoIskiv** [entrecode/angular-state-loader#1]
Hi

I was using your lib and encountered an issue. In my app I have redirect to 404 page in a case some resolve function rejected but with your lib when I clicked back button in browser I saw the spinner that never hides although '$stateChangeSuccess' event fired. I think it might be caused by assigning timer promise to timer [variable](https://github.com/entrecode/angular-state-loader/blob/master/angular-state-loader.js#L51) as in this case you override reference to previous timer instance, so it's never cancelled. I would suggest to make timer variable as an array of timer instances and cancel all of them in loop once '$stateChangeSuccess' event fired. Also I would suggest to cancel timers on destroy event.

Regards,
Mykhailo

**Comment by konkissner** [comment]
Sorry for the late reply. Unfortunately, I cannot reproduce this issue. Do you still have the problem / using the plugin and might send me a small example?
