### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by jijishthomas** [entrecode/angular-state-loader#3]
I have installed the module. but not showing the loading animation!

**Comment by felixroos** [comment]
did you include material icons or defined a custom template, like described in the readme?

**Comment by jijishthomas** [comment]
yes like this
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

**Comment by jijishthomas** [comment]
i have used default material icons, 
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**Comment by felixroos** [comment]
can you provide a plunkr to show how you use the loader in your code?

**Comment by jijishthomas** [comment]
i am having a SPA, with many states, i will tell you what i have done, 
added these to index
 `<script src="loader/angular-state-loader.js" type="text/javascript"></script>
<link href="loader/angular-state-loader.css" type="text/css" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
`

then in my app.js 'ec.stateloader'is added as dependecy
then  `<state-loader></state-loader>`
is added in index,html

**Comment by felixroos** [comment]
Sorry but this info is not enough to get the whole picture of how you use it. Without a plunkr/jsfiddle/gist it is impossible for me to see the mistake. You can also run the included [demo](https://github.com/entrecode/angular-state-loader/blob/master/demo/index.html), after running "bower install" inside the demo folder.

**Comment by jijishthomas** [comment]
i have seen the demo, 
To display the default loader, is there anything else to do, other than i had mentioned earlier?

**Comment by konkissner** [comment]
I am closing this issue.
If you can provide a jsfiddle, I'll reopen it.
